FROM openjdk:11
COPY . /src/java
WORKDIR /src/java
EXPOSE 8082
CMD ["java","-jar","teste-1.0-SNAPSHOT-jar-with-dependencies.jar"]
#ENTRYPOINT ["java","-jar","teste-1.0-SNAPSHOT-jar-with-dependencies.jar"]
